package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.42

import (
	"context"
	"fmt"

	"github.com/joaoianuci/go-graphql/graph/model"
)

// Courses is the resolver for the courses field.
func (r *categoryResolver) Courses(ctx context.Context, obj *model.Category) ([]*model.Course, error) {
	courses, err := r.CourseDB.FindByCategoryID(obj.ID)
	if err != nil {
		return nil, err
	}

	var result []*model.Course
	for _, course := range courses {
		result = append(result, &model.Course{
			ID:          course.ID,
			Name:        course.Name,
			Description: &course.Description,
		})
	}

	return result, nil
}

// Category is the resolver for the category field.
func (r *courseResolver) Category(ctx context.Context, obj *model.Course) (*model.Category, error) {
	category, err := r.CategoryDB.FindByCourseID(obj.ID)
	if err != nil {
		return nil, err
	}

	return &model.Category{
		ID:          category.ID,
		Name:        category.Name,
		Description: &category.Description,
	}, nil
}

// Lessons is the resolver for the lessons field.
func (r *courseResolver) Lessons(ctx context.Context, obj *model.Course) ([]*model.Lesson, error) {
	lessons, err := r.LessonDB.FindByCourseID(obj.ID)
	if err != nil {
		return nil, err
	}

	var result []*model.Lesson
	for _, lesson := range lessons {
		result = append(result, &model.Lesson{
			ID:          lesson.ID,
			Name:        lesson.Name,
			Description: &lesson.Description,
			Content:     lesson.Content,
		})
	}

	return result, nil
}

// Course is the resolver for the course field.
func (r *lessonResolver) Course(ctx context.Context, obj *model.Lesson) (*model.Course, error) {
	// course with lessons
	course, err := r.CourseDB.FindByLessonID(obj.ID)
	if err != nil {
		return nil, err
	}

	return &model.Course{
		ID:          course.ID,
		Name:        course.Name,
		Description: &course.Description,
	}, nil
}

// CreateCategory is the resolver for the createCategory field.
func (r *mutationResolver) CreateCategory(ctx context.Context, input model.NewCategoryInput) (*model.Category, error) {
	category, err := r.CategoryDB.Create(input.Name, *input.Description)
	if err != nil {
		return nil, err
	}

	return &model.Category{
		ID:          category.ID,
		Name:        category.Name,
		Description: &category.Description,
	}, nil
}

// DeleteCategory is the resolver for the deleteCategory field.
func (r *mutationResolver) DeleteCategory(ctx context.Context, id string) (bool, error) {
	status, err := r.CategoryDB.Delete(id)
	if err != nil {
		return false, err
	}

	return status, nil
}

// CreateCourse is the resolver for the createCourse field.
func (r *mutationResolver) CreateCourse(ctx context.Context, input model.NewCourseInput) (*model.Course, error) {
	course, err := r.CourseDB.Create(input.Name, *input.Description, input.CategoryID)
	if err != nil {
		return nil, err
	}

	return &model.Course{
		ID:          course.ID,
		Name:        course.Name,
		Description: &course.Description,
	}, nil
}

// CreateLesson is the resolver for the createLesson field.
func (r *mutationResolver) CreateLesson(ctx context.Context, input model.NewLessonInput) (*model.Lesson, error) {
	lesson, err := r.LessonDB.Create(input.Name, *input.Description, input.CourseID, input.Content)
	if err != nil {
		return nil, err
	}

	return &model.Lesson{
		ID:          lesson.ID,
		Name:        lesson.Name,
		Description: &lesson.Description,
		Content:     lesson.Content,
	}, nil
}

// Categories is the resolver for the categories field.
func (r *queryResolver) Categories(ctx context.Context) ([]*model.Category, error) {
	categories, err := r.CategoryDB.FindAll()
	if err != nil {
		return nil, err
	}

	var result []*model.Category
	for _, category := range categories {
		result = append(result, &model.Category{
			ID:          category.ID,
			Name:        category.Name,
			Description: &category.Description,
		})
	}

	return result, nil
}

// Category is the resolver for the category field.
func (r *queryResolver) Category(ctx context.Context, id string) (*model.Category, error) {
	panic(fmt.Errorf("not implemented: Category - category"))
}

// Courses is the resolver for the courses field.
func (r *queryResolver) Courses(ctx context.Context) ([]*model.Course, error) {
	courses, err := r.CourseDB.FindAll()
	if err != nil {
		return nil, err
	}

	var result []*model.Course
	for _, course := range courses {
		result = append(result, &model.Course{
			ID:          course.ID,
			Name:        course.Name,
			Description: &course.Description,
		})
	}

	return result, nil
}

// Course is the resolver for the course field.
func (r *queryResolver) Course(ctx context.Context, id string) (*model.Course, error) {
	panic(fmt.Errorf("not implemented: Course - course"))
}

// Lessons is the resolver for the lessons field.
func (r *queryResolver) Lessons(ctx context.Context) ([]*model.Lesson, error) {
	lessons, err := r.LessonDB.FindAll()
	if err != nil {
		return nil, err
	}

	var result []*model.Lesson
	for _, lesson := range lessons {
		result = append(result, &model.Lesson{
			ID:          lesson.ID,
			Name:        lesson.Name,
			Description: &lesson.Description,
			Content:     lesson.Content,
		})
	}

	return result, nil
}

// Lesson is the resolver for the lesson field.
func (r *queryResolver) Lesson(ctx context.Context, id string) (*model.Lesson, error) {
	lesson, err := r.LessonDB.FindByID(id)
	if err != nil {
		return nil, err
	}

	return &model.Lesson{
		ID:          lesson.ID,
		Name:        lesson.Name,
		Description: &lesson.Description,
		Content:     lesson.Content,
	}, nil
}

// Category returns CategoryResolver implementation.
func (r *Resolver) Category() CategoryResolver { return &categoryResolver{r} }

// Course returns CourseResolver implementation.
func (r *Resolver) Course() CourseResolver { return &courseResolver{r} }

// Lesson returns LessonResolver implementation.
func (r *Resolver) Lesson() LessonResolver { return &lessonResolver{r} }

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type categoryResolver struct{ *Resolver }
type courseResolver struct{ *Resolver }
type lessonResolver struct{ *Resolver }
type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
