// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type NewCategoryInput struct {
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
}

type NewCourseInput struct {
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
	CategoryID  string  `json:"categoryId"`
}

type NewLessonInput struct {
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
	CourseID    string  `json:"courseId"`
	Content     string  `json:"content"`
}

type Query struct {
}
